kind: Component
spec:
  type: Lambda
  lifecycle: prod
  owner: Field_Engineering
  system: Platform_Demo
  dependsOn:
    - component:boutique-adservice
    - component:boutique-checkoutservice
    - component:boutique-currencyservice
    - component:boutique-emailservice
    - component:boutique-loadgenerator
    - component:boutique-paymentservice
    - component:boutique-productcatalogservice
  providesApis:
    - petstore
    - starwars-graphql
apiVersion: backstage.io/v1alpha1
metadata:
  name: test_01_app
  description: My New Lambda
  tags: 
    - python
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: idp-testing/test_01_app
    harness.io/project-url: https://app.harness.io/ng/account/6_vVHzo9Qeu9fXvj-AcbCQ/home/orgs/SE_Sandbox/projects/test_01_app/details
    harness.io/cd-serviceId: test_01_app
